### ISSUE TITLE
other registers inaccessible

### ISSUE THREAD

**Issue by barelyhuman** [rsms/rsm#1]
## What 
An attempt to a simple loop / partial fibonacci series 

## The bug / issue
The other registers seem to be inaccessible during calculations, in this case the `R3` register shows as `R6` in the Log 

## Screenshots
<img width="1440" alt="Screenshot 2022-02-25 at 11 12 50 AM" src="https://user-images.githubusercontent.com/43572006/155660872-9031228a-48c5-4db2-94a2-0ab6b86c378b.png">

**Comment by barelyhuman** [comment]
I understand if this is still being worked on, you can ignore this issue in that case :)

**Comment by tanishqkancharla** [comment]
wdym inaccessible? Does the program fail when you try to use `R6`?

**Comment by rsms** [comment]
Sorry, the web version is super old. I'm doing so much work on the main implementation that I've decided to leave the old web version as-is for now.

I'm really happy to see that you're playing with RSM! I'd recommend making your own builds locally as that also includes useful runtime information. Try cloning the repo and making a debug build with `./build.sh -debug` (macOS or Linux/WSL) — this will print a lot of information as you're running your programs.

Here's an extended program based on yours:

```
// set -R1=1 to enable printing
const STDOUT = 1
const ZERO_CHAR = 0x30
data msg_str = "n = "
data lf_str = "\n"

fun fib(n i32, print_loop i1) i32 {
  // if n == 0 { n = 100 } -- default argument value to 100
  if R0 start
  R0 = 100
start:
  // use caller-owned registers to avoid push/pop around calls
  R19 = R0
  R20 = 0
  R21 = 1
  R22 = 1 // loop counter
  R23 = R1 // print_loop

b1:
  ifz R23 b2 // skip printing unless print_loop==true
  call print msg_str 4
  call print_u64 R19
  call print lf_str 1
b2:
  R2 = R20 + R21
  R20 = R21
  R21 = R2
  R19 = R19 - 1
  R22 = R22 + 1
  if R19 b1

  ret
}

// print_u64 writes a u64 as decimal number to stdout.
// returns 0 on success, 1 on failed or short write.
fun print_u64(value i64) ok i1 {
  // largest u64 base-10 is 20 bytes long "18446744073709551615"
  SP = sub SP 24  // reserve 24B of stack space (8B aligned)
  R1 = SP + 24    // define string storage memory address
loop:
  R1 = R1 - 1     // decrement storage address
  R2 = R0 % 10 ; R2 = R2 + ZERO_CHAR // ch = '0' + (value % 10)
  store1 R2 R1 0  // store byte R2 at address R1
  R0 = R0 / 10    // value = value / 10
  if R0 loop      // loop if there's another digit to print
// end
  R2 = SP + 24 ; R2 = R2 - R1 // count bytes (start - end)
  R0 = write R1 R2 STDOUT
  SP = add SP 24 // restore stack pointer
}

// returns 0 on success, 1 on failed or short write
fun print(addr i64, size i64) ok i1 {
  R0 = write R0 R1 STDOUT
  R0 = lts R0 R1
}
```

Example:

```
out/rsm -rd -R0=15 -R1=1 fib.rsm
n = 15
n = 14
n = 13
n = 12
n = 11
n = 10
n = 9
n = 8
n = 7
n = 6
n = 5
n = 4
n = 3
n = 2
n = 1
Execution finished in 250us
register state:
                      R0                   R1                   R2                   R3
U64                  0x0                  0x1                0x3db                  0x0
U64                    0                    1                  987                    0
S64                    0                    1                  987                    0
S32                    0                    1                  987                    0
S16                    0                    1                  987                    0
S8                     0                    1                  -37                    0
```

**Comment by barelyhuman** [comment]
this was working on the local version and not on the web one

@tanishqkancharla , if you check the the Operators being run on the right, it says move r2 from r6 when the code of the left is trying to get the value of r3 and not r6 

@rsms yeah, you did reply for the same on twitter, i just forgot to close the issue

**Comment by rsms** [comment]
I wrote a full-featured fib implementation thanks to this and added it as an example: https://github.com/rsms/rsm/blob/4323bd7e687f619330b528705b28cff56e0e0b10/examples/fib.rsm

:•)
